questionnaireeleve:
    pattern:  /etape3/{questionnaire}/{eleve}
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:index" }

questionnaireeleve_etape1:
    pattern:  /etape1
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:indexEtape1" }

questionnaireeleve_etape1_recup_questionnaire:
    pattern:  /etape1/recupQuestionnaire
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:indexEtape1RecupQuestionnaire" }

questionnaireeleve_etape2:
    pattern:  /etape2
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:indexEtape2" }

questionnaireeleve_show:
    pattern:  /{questionnaire}/{eleve}/show
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:show" }

questionnaireeleve_new:
    pattern:  /new
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:new" }

questionnaireeleve_create:
    pattern:  /create
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:create" }
    requirements: { _method: post }

questionnaireeleve_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:edit" }

questionnaireeleve_update:
    pattern:  /{id}/update
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:update" }
    requirements: { _method: post }

questionnaireeleve_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EDiffAdminBundle:QuestionnaireEleve:delete" }
    requirements: { _method: post }
