<?php

namespace EDiff\Bundle\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionRepository extends EntityRepository
{
	public function getSearch($page, $nb_per_page, $niveau, $matiere, $motcle)
    {
        $qb = $this->createQueryBuilder('q');

        if($niveau != -1) {
        	$qb->andWhere('q.niveau = :niveau')
        	   ->setParameter('niveau', $niveau);
        }
        
    	if($matiere != -1) {
        	$qb->andWhere('q.matiere = :matiere')
        	   ->setParameter('matiere', $matiere);
        }
        
    	if($motcle != "Mot clé") {
        	$qb->andWhere( $qb->expr()->like('q.libelle', $qb->expr()->literal('%' . $motcle . '%')) );
        }
        	
        $qb	->setFirstResult($page)
    		->setMaxResults($nb_per_page);
        	
        // Enfin, on retourne le résultat.
        return $qb->getQuery()
                   ->getResult();
    }
    
	public function getAllSearch($niveau, $matiere, $motcle)
    {
        $qb = $this->createQueryBuilder('q');

        if($niveau != -1) {
        	$qb->andWhere('q.niveau = :niveau')
        	   ->setParameter('niveau', $niveau);
        }
        
    	if($matiere != -1) {
        	$qb->andWhere('q.matiere = :matiere')
        	   ->setParameter('matiere', $matiere);
        }
        	
        // Enfin, on retourne le résultat.
        return $qb->getQuery()
                   ->getResult();
    }
}